### ISSUE TITLE
[🚀] Add Google-SSO Account to Config

### ISSUE THREAD

**Issue by p0w1** [juice-shop/juice-shop#1281]
# :rocket: Feature request

### Description

Currently it is not possible to use the Google-Login for custom domains.

### Solution ideas

Add the "clientId" in /frontend/src/app/login/login.component.ts to the config-File.

**Comment by bkimminich** [comment]
That's actually a brilliant idea! 👍 ... Making the `authorizedRedirectURIs` configurable as well would make OAuth completely customizable.

**Comment by bkimminich** [comment]
You can use the following config properties now to customize your OAuth provider app and allowed URLs:

```
application:
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'http://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'http://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'http://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'http://juice-shop-staging.herokuapp.com' }
      - { uri: 'http://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'http://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'http://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'http://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'http://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'http://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'http://localchromeos.owasp-juice.shop' }
```

Feel free to test it on `develop` branch and let me know if this is what you were looking for!
