### ISSUE TITLE
Multi-Arch DockerHub builds [🚀] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1404]
Following the blog post by @everflux in https://www.trion.de/news/2019/10/14/docker-multi-arch-dockerhub.html I've implemented a multi-arch Docker build process for Juice Shop. There are some unsolved issues and some missing functionality still, but I'm not sure my Docker skills are sufficient to address these.

1. :bug: The `snapshot-arm64v8` tag is downloading the `x64` modules for `iltorb`, `libxml2js` and `sqlite3` because it seems to think it is running on an x64 architecture. This is a dealbreaker as the resulting image simply cannot work on e.g. a RasPi3 or other ARM-chip computer.
2. 💡 Currently the manifest is only configured for the `snapshot` builds from `develop` branch. If 1. gets eventually fixed, building `latest` from `master` and `vX.Y.Z` from Git tags would be needed. @everflux recommended to stick to one manifest file and replace the tag names e.g. via `sed` in the `pre_build` hook.

The additional hooks, Dockerfile for Arm64v8 and manifest file are available on https://github.com/bkimminich/juice-shop/tree/develop for anyone who wants to assist in this endeavor.

**Comment by J12934** [comment]
I guess the best / most stable thing to do is do run the docker builds on travis, as we actually have access to ARM CPU's there.

**Comment by bkimminich** [comment]
So, introducing a new build stage "docker" and once that works switch off the Automated Builds on DockerHub?

**Comment by bkimminich** [comment]
```
  - stage: docker
    if: "(branch = develop) AND NOT type = pull_request"
    install: docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg
      BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ” -t bkimminich/juice-shop:snapshot-amd64
      .
    script:
    - echo "$DOCKER_ACCESS_TOKEN" | docker login -u bkimminich --password-stdin
    - docker push bkimminich/juice-shop:snapshot-amd64
    after_success:
    - curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
    - chmod +x manifest-tool
    - "./manifest-tool push from-spec multi-arch-manifest.yaml"
```

This attempt covers the regular Docker build plus
* injecting the Git ref/date meta data (previously done via `pre_build` hook)
* login to DockerHub and pushing the image
* Downloading the manifest tool and pushing it to DockerHub (previously via `post_push` hook)

All that currently in a separate stage (which limits it to the default matrix job (Node 14 on Amd64 Linux) and only for `develop` branch. Once this works, it could be extended to also run on `master`, tag pushes and finally on Node 14 on Arm64 matrix job.
