### ISSUE TITLE
Add x86 Windows 32bit build variant on AppVeyor

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#163]
```
platform:
  - x64
  - x86
install:
  - ps: Install-Product node $env:nodejs_version {platform}
[...]
  - node_modules\.bin\grunt package-win-{platform}
[...]
artifacts:
  - path: dist\juice-shop-*_node4_win_{platform}.zip
```
