### ISSUE TITLE
🐛 BASE_PATH configuration failing to load all resources when used with a basic reverse proxy setup

### ISSUE THREAD

**Issue by tomdaley92** [juice-shop/juice-shop#1796]
# :bug: Bug report

## Description

Passing the `BASE_PATH` environment variable per the customization docs does not work properly behind a reverse proxy with a standard `path prefix` rule. There are still some resources that are trying to be loaded from the root `/` instead of from `$BASE_PATH/`. Some resource are loading correctly (page background color and cookies consent pop-up load just fine).

### Is this a regression?

I'm not sure. But I think [this](https://github.com/juice-shop/juice-shop/pull/1356) PR was supposed to "fix" it or was an attempt at dealing with this

## :microscope: Minimal Reproduction
 
See Environment section for minimal docker-compose/ docker-swarm configuration to reproduce

## :fire: Exception or Error

![Screen Shot 2022-04-21 at 12 31 19 PM](https://user-images.githubusercontent.com/12147036/164539935-b1ffa294-0951-49a5-afe3-b7ca881c006a.png)

As you can see in the above screenshot, many resources load fine while using a basePath of `player-1`, however starting with `runtime.js` the application tells the browser to load it from root.

![Screen Shot 2022-04-21 at 12 31 45 PM](https://user-images.githubusercontent.com/12147036/164539944-e9033a78-985a-4164-b67d-45ed2b86dc81.png)

As you can see above, when I manually try to load `runtime.js` from `/player-1/runtime.js` it loads correctly.

## :deciduous_tree: Your Environment

I want to be able to set up multiple juice-shop instances behind a single hostname, however the added `BASE_PATH` configuration does not seem implemented correctly. Here is a minimal docker-compose file that I am using with `docker-swarm`. I have omitted the traefik configuration here as it is not relevant.

```yaml
# docker-compose.yaml

version: '3.8'

services:

  shop-1:
    image: bkimminich/juice-shop
    environment:
      - PORT=3001
      - BASE_PATH=/player-1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.shop-1.loadbalancer.server.port=3001
        - traefik.http.services.shop-1.loadbalancer.sticky.cookie=true
        - traefik.http.routers.shop-1.rule=Host(`gameday.example.net`) && PathPrefix(`/player-1`)
        - traefik.http.routers.shop-1.service=shop-1
    networks:
      - traefik_network

networks:
  traefik_network:
    external: True
    name: traefik_network
```

### Additional Information

This is not specific to Traefik or the reverse proxy or the web browser. Juice shop should correctly use the `basePath` config item for ALL relative links/resources. It looks like the main `index.html` or equivalent is telling the browser to look from  root `/` not taking the `base_path` into account perhaps?
