### ISSUE TITLE
unable to download the image bkimminich/juice-shop

### ISSUE THREAD

**Issue by marlonfrank30** [juice-shop/juice-shop#2434]
hi,
I have already created auth tokens and serviceaccounts to download this image in quay.io for my k8s cluster like I have always done however lately I keep getting [unauthorized access to the requested source is not authorized]
```
alias oc=kubectl
marlon@k8s-master:~/juice-shop$ cat docker-auth-secret.yaml
---
apiVersion: v1
data:
  .dockerconfigjson: removed
kind: Secret
metadata:
  name: docker.io
  namespace: juice-shop
  uid: b094e390-f192-4cf1-b804-ac1b1d571883
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: removed
kind: Secret
metadata:
  name: quay.io
  namespace: juice-shop
  uid: 4d3a78d2-d736-4b1b-be45-4c7a45b6f25f
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: juice-shop
  name: quay.io
  namespace: juice-shop
  uid: 052fb0f4-3d50-11e5-b066-42010af0d7b6
imagePullSecrets:
  - name: quay.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker.io
  namespace: juice-shop
  uid: 052fb0f4-3d50-11e5-b066-42010af0d7b7
imagePullSecrets:
  - name: docker.io
marlon@k8s-master:~/juice-shop$

marlon@k8s-master:~/juice-shop$ oc get sa,secret -n juice-shop
NAME                       SECRETS   AGE
serviceaccount/default     0         11m
serviceaccount/docker.io   0         11m
serviceaccount/quay.io     0         11m

NAME               TYPE                             DATA   AGE
secret/docker.io   kubernetes.io/dockerconfigjson   1      11m
secret/quay.io     kubernetes.io/dockerconfigjson   1      11m
marlon@k8s-master:~/juice-shop$

marlon@k8s-master:~/juice-shop$ cat juice-shop-deployment.yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: juice-shop
  name: juice-shop
spec:
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
  selector:
    matchLabels:
      app: juice-shop
---
kind: Service
apiVersion: v1
metadata:
   namespace: juice-shop
   name: juice-shop
spec:
  type: ClusterIP
  selector:
    app: juice-shop
  ports:
  - name: http
    port: 8000
    targetPort: 3000
---
```
```

marlon@k8s-master:~/juice-shop$ oc describe pod juice-shop-67bc95fb88-66jln -n juice-shop
Name:             juice-shop-67bc95fb88-66jln
Namespace:        juice-shop
Priority:         0
Node:             k8s-node1/10.1.10.92
Start Time:       Thu, 23 Jan 2025 19:29:22 +0000
Labels:           app=juice-shop
                  pod-template-hash=67bc95fb88
Annotations:      <none>
Status:           Pending
IP:               10.244.2.168
IPs:
  IP:           10.244.2.168
Controlled By:  ReplicaSet/juice-shop-67bc95fb88
Containers:
  juice-shop:
    Container ID:
    Image:          bkimminich/juice-shop
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lz8sq (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  kube-api-access-lz8sq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  78s                default-scheduler  Successfully assigned juice-shop/juice-shop-67bc95fb88-66jln to k8s-node1
  Warning  Failed     32s                kubelet            Failed to pull image "bkimminich/juice-shop": initializing source docker://quay.io/bkimminich/juice-shop:latest: reading manifest latest in quay.io/bkimminich/juice-shop: unauthorized: access to the requested resource is not authorized
  Warning  Failed     32s                kubelet            Error: ErrImagePull
  Normal   BackOff    32s                kubelet            Back-off pulling image "bkimminich/juice-shop"
  Warning  Failed     32s                kubelet            Error: ImagePullBackOff
  Normal   Pulling    20s (x2 over 77s)  kubelet            Pulling image "bkimminich/juice-shop"
```

is there anything that I am missing here? anything with the way the image is being uploaded that has changed the permissions?
I'd love to know
thank you
