### ISSUE TITLE
[🚀] Hacking Instructor

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#440]
1. User selects a challenge from the Score Board
2. The _Hacking Instructor_ guides the user through the challenge step-by-step...
3. ...until the challenge is solved

* Gives some soft hints first and allows to ask for more help up to full solution walkthrough
* The "wasp" from the ebook logo could act as the instructor avatar/agent

**Comment by bkimminich** [comment]
## Storyboard

### Select Challenge
![image](https://user-images.githubusercontent.com/3531020/35459602-25dcd8c0-02e1-11e8-9147-f74d3160a01b.png)

### Helpful Wasp shows up and gives a hint
![image](https://user-images.githubusercontent.com/3531020/35459607-2bbdef90-02e1-11e8-9b48-bb976fcb83d0.png)

### Helpful Wasp observes regular behavior
![image](https://user-images.githubusercontent.com/3531020/35459610-2d93fb16-02e1-11e8-9fa9-8dc63ba399a9.png)

### Wasp goes to screen edge waiting to be called for more help
![image](https://user-images.githubusercontent.com/3531020/35459617-336b910c-02e1-11e8-9299-cc13509dba45.png)

### Helpful Wasp gives hint what to do next
![image](https://user-images.githubusercontent.com/3531020/35459612-2f5c1474-02e1-11e8-9709-0217fcbb39e5.png)

### Another smart remark
![image](https://user-images.githubusercontent.com/3531020/35459614-310f72d4-02e1-11e8-8c38-1acff4766802.png)

### Wasp goes back to screen edge
![image](https://user-images.githubusercontent.com/3531020/35459617-336b910c-02e1-11e8-9299-cc13509dba45.png)

### ...

**Comment by bkimminich** [comment]
## File Format for Hacking Instructions
```yaml
challenges:
  - name: XSS Tier 1
    hints:
      - text: Well, I prefer stripes, but let‘s do some cross site scripting! First, let‘s search for „wasp“ in the Search box at the top of the page!
        page: score-board
        fixture:
          - type: id
          - value: XSS Tier 1
        position: right
      - text: Good! You can see, the search value you typed also appears on top of the result list so you remember what it was! How convenient…
        page: search
        fixture:
          - type: ng-bind-html
          - value: searchQuery
        position: right
        hideAfterHint: true
      - text: Now, search for this instead and observe what happens… „<h1>wasp“
        page: search
        fixture:
          - type: ng-model
          - value: searchQuery
        position: bottom
      - text: Whoops, what happened here? You might want to inspect the text with your Browser DevTools to find out! Click me when you need more help!
        page: search
        fixture:
          - type: ng-bind-html
          - value: searchQuery
        position: right
        hideAfterHint: true
      ...
```
